package com.novalang.bukkit.types.entity;

import com.novalang.bukkit.Requires;
import com.novalang.bukkit.paper.entity.PaperEntityReflection;
import com.novalang.runtime.host.JavaTypeRef;
import com.novalang.runtime.host.JavaTypes;
import java.lang.reflect.Method;
import org.bukkit.Color;

/** 1.19.4+ TextDisplay 的 Fluxon 函数契约。 */
@Requires(classes = {"org.bukkit.entity.TextDisplay", "org.bukkit.entity.TextDisplay$TextAlignment"}, methods = {"org.bukkit.entity.TextDisplay#getText", "org.bukkit.entity.TextDisplay#setText", "org.bukkit.entity.TextDisplay#getLineWidth", "org.bukkit.entity.TextDisplay#setLineWidth", "org.bukkit.entity.TextDisplay#getBackgroundColor", "org.bukkit.entity.TextDisplay#setBackgroundColor", "org.bukkit.entity.TextDisplay#getTextOpacity", "org.bukkit.entity.TextDisplay#setTextOpacity", "org.bukkit.entity.TextDisplay#isShadowed", "org.bukkit.entity.TextDisplay#setShadowed", "org.bukkit.entity.TextDisplay#isSeeThrough", "org.bukkit.entity.TextDisplay#setSeeThrough", "org.bukkit.entity.TextDisplay#isDefaultBackground", "org.bukkit.entity.TextDisplay#setDefaultBackground", "org.bukkit.entity.TextDisplay#getAlignment", "org.bukkit.entity.TextDisplay#setAlignment"})
public final class NovaTextDisplay {
    private static final String TYPE = "org.bukkit.entity.TextDisplay";
    private static final String ALIGNMENT = "org.bukkit.entity.TextDisplay$TextAlignment";
    private NovaTextDisplay() { }
    public static void register(JavaTypes.Builder builder) {
        Class<?> type = PaperEntityReflection.type(NovaTextDisplay.class, TYPE); Class<?> alignment = PaperEntityReflection.type(NovaTextDisplay.class, ALIGNMENT);
        Method text = PaperEntityReflection.method(type, "getText"); Method setText = PaperEntityReflection.method(type, "setText", String.class); Method width = PaperEntityReflection.method(type, "getLineWidth"); Method setWidth = PaperEntityReflection.method(type, "setLineWidth", Integer.TYPE); Method background = PaperEntityReflection.method(type, "getBackgroundColor"); Method setBackground = PaperEntityReflection.method(type, "setBackgroundColor", Color.class); Method opacity = PaperEntityReflection.method(type, "getTextOpacity"); Method setOpacity = PaperEntityReflection.method(type, "setTextOpacity", Byte.TYPE); Method shadow = PaperEntityReflection.method(type, "isShadowed"); Method setShadow = PaperEntityReflection.method(type, "setShadowed", Boolean.TYPE); Method seeThrough = PaperEntityReflection.method(type, "isSeeThrough"); Method setSeeThrough = PaperEntityReflection.method(type, "setSeeThrough", Boolean.TYPE); Method defaultBackground = PaperEntityReflection.method(type, "isDefaultBackground"); Method setDefaultBackground = PaperEntityReflection.method(type, "setDefaultBackground", Boolean.TYPE); Method getAlignment = PaperEntityReflection.method(type, "getAlignment"); Method setAlignment = PaperEntityReflection.method(type, "setAlignment", alignment);
        JavaTypeRef nullableString = JavaTypeRef.javaType(String.class).nullable(); JavaTypeRef nullableColor = JavaTypeRef.javaType(Color.class).nullable();
        builder.extension(type, "text", f -> f.returns(nullableString).invoke(a -> PaperEntityReflection.invoke(text, a[0]))); builder.extension(type, "setText", f -> f.param("text", nullableString).returns(Void.TYPE).invoke(a -> PaperEntityReflection.invoke(setText, a[0], a[1]))); builder.extension(type, "lineWidth", f -> f.returns(Integer.class).invoke(a -> PaperEntityReflection.invoke(width, a[0]))); builder.extension(type, "setLineWidth", f -> f.param("width", Integer.class).returns(Void.TYPE).invoke(a -> PaperEntityReflection.invoke(setWidth, a[0], a[1]))); builder.extension(type, "backgroundColor", f -> f.returns(nullableColor).invoke(a -> PaperEntityReflection.invoke(background, a[0]))); builder.extension(type, "setBackgroundColor", f -> f.param("color", nullableColor).returns(Void.TYPE).invoke(a -> PaperEntityReflection.invoke(setBackground, a[0], a[1]))); builder.extension(type, "textOpacity", f -> f.returns(Integer.class).invoke(a -> ((Byte) PaperEntityReflection.invoke(opacity, a[0])).intValue())); builder.extension(type, "setTextOpacity", f -> f.param("opacity", Integer.class).returns(Void.TYPE).invoke(a -> PaperEntityReflection.invoke(setOpacity, a[0], ((Integer) a[1]).byteValue())));
        flag(builder, type, "isShadowed", "setShadowed", shadow, setShadow); flag(builder, type, "isSeeThrough", "setSeeThrough", seeThrough, setSeeThrough); flag(builder, type, "isDefaultBackground", "setDefaultBackground", defaultBackground, setDefaultBackground);
        builder.extension(type, "alignment", f -> f.returns(JavaTypeRef.javaType(alignment)).invoke(a -> PaperEntityReflection.invoke(getAlignment, a[0]))); builder.extension(type, "setAlignment", f -> f.param("alignment", JavaTypeRef.javaType(alignment)).returns(Void.TYPE).invoke(a -> PaperEntityReflection.invoke(setAlignment, a[0], a[1]))); builder.extension(type, "setAlignment", f -> f.param("alignment", String.class).returns(Void.TYPE).invoke(a -> set(setAlignment, alignment, a[0], (String) a[1])));
    }
    private static void flag(JavaTypes.Builder builder, Class<?> type, String getterName, String setterName, Method getter, Method setter) { builder.extension(type, getterName, f -> f.returns(Boolean.class).invoke(a -> PaperEntityReflection.invoke(getter, a[0]))); builder.extension(type, setterName, f -> f.param("value", Boolean.class).returns(Void.TYPE).invoke(a -> PaperEntityReflection.invoke(setter, a[0], a[1]))); }
    private static Object set(Method method, Class<?> type, Object target, String name) { Object value = PaperEntityReflection.enumValue(type, name); if (value != null) { return PaperEntityReflection.invoke(method, target, value); } return null; }
}
