pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'novalang'

include 'nova-runtime-api'
include 'nova-runtime-types'
include 'nova-compiler'
include 'nova-ir'
include 'nova-runtime'
include 'nova-runtime-workspace'
include 'nova-cli'
include 'nova-lsp'
include 'nova-example'
include 'nova-script'
include 'nova-bukkit'
include 'nova-playground'
include 'nova-benchmarks'
include 'nova-json-gson'
include 'nova-json-fastjson2'
include 'nova-yaml-snakeyaml'
include 'nova-yaml-bukkit'
include 'nova-mock'
